name: smart_data_hub
channels:
  - pypi
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - dash==3.2.0
    - dash-bootstrap-components==2.0.4
    - gempy==2025.2.0
    - pandas==2.3.3
    - pyvista==0.45.3
    - pyyaml==6.0.3
    - scipy==1.15.3
    - ruamel.yaml==0.18.16
    - trame==3.12.0
    - trame-vtk==2.10.0
    - trame-vuetify==3.1.0
    - vtk==9.4.2